-- MySQL Script generated by MySQL Workbench
-- Wed Jun  7 20:32:11 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema binariom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema binariom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `binariom` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `binariom` ;

-- -----------------------------------------------------
-- Table `binariom`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `binariom`.`perfil` ;

CREATE TABLE IF NOT EXISTS `binariom`.`perfil` (
  `id` INT(2) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `binariom`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `binariom`.`usuario` ;

CREATE TABLE IF NOT EXISTS `binariom`.`usuario` (
  `matricula` VARCHAR(5) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(7) NOT NULL,
  `setor` VARCHAR(5) NOT NULL,
  `telefone` INT(11) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `id_perfil` INT(2) NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_usuario_perfil1_idx` (`id_perfil` ASC),
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `binariom`.`perfil` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `binariom`.`equipamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `binariom`.`equipamento` ;

CREATE TABLE IF NOT EXISTS `binariom`.`equipamento` (
  `etiqueta` VARCHAR(4) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`etiqueta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `binariom`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `binariom`.`cliente` ;

CREATE TABLE IF NOT EXISTS `binariom`.`cliente` (
  `matricula` VARCHAR(5) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `setor` VARCHAR(5) NOT NULL,
  `sala` INT(3) NOT NULL,
  `telefone` INT(11) NOT NULL,
  `senha` VARCHAR(5) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `binariom`.`chamado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `binariom`.`chamado` ;

CREATE TABLE IF NOT EXISTS `binariom`.`chamado` (
  `bin` INT(6) ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(500) NOT NULL,
  `atendimento` VARCHAR (500) NULL DEFAULT '--ATENDIMENTO REALIZADO--',
  `status` VARCHAR(45) NULL DEFAULT 'Aberto',
  `prioridade` VARCHAR(45) NULL DEFAULT 'NORMAL',
  `data_abertura` DATETIME DEFAULT NOW(),
  `data_resolvido` DATETIME DEFAULT NOW() ON UPDATE NOW(),
  `usuario_matricula` VARCHAR(5) NOT NULL,
  `equipamento_etiqueta` VARCHAR(4) NOT NULL,
  `cliente_matricula` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`bin`),
  INDEX `fk_chamado_usuario1_idx` (`usuario_matricula` ASC),
  INDEX `fk_chamado_equipamento1_idx` (`equipamento_etiqueta` ASC),
  INDEX `fk_chamado_cliente1_idx` (`cliente_matricula` ASC),
  CONSTRAINT `fk_chamado_usuario1`
    FOREIGN KEY (`usuario_matricula`)
    REFERENCES `binariom`.`usuario` (`matricula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_chamado_equipamento1`
    FOREIGN KEY (`equipamento_etiqueta`)
    REFERENCES `binariom`.`equipamento` (`etiqueta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_chamado_cliente1`
    FOREIGN KEY (`cliente_matricula`)
    REFERENCES `binariom`.`cliente` (`matricula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `binariom`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `binariom`.`menu` ;

CREATE TABLE IF NOT EXISTS `binariom`.`menu` (
  `id` INT(2) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `link` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `binariom`.`menu_perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `binariom`.`menu_perfil` ;

CREATE TABLE IF NOT EXISTS `binariom`.`menu_perfil` (
  `id_menu` INT(2) NOT NULL,
  `id_perfil` INT(2) NOT NULL,
  PRIMARY KEY (`id_menu`, `id_perfil`),
  INDEX `fk_menu_has_perfil_perfil1_idx` (`id_perfil` ASC),
  INDEX `fk_menu_has_perfil_menu1_idx` (`id_menu` ASC),
  CONSTRAINT `fk_menu_has_perfil_menu1`
    FOREIGN KEY (`id_menu`)
    REFERENCES `binariom`.`menu` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_menu_has_perfil_perfil1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `binariom`.`perfil` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `binariom`.`estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `binariom`.`estoque` ;

CREATE TABLE IF NOT EXISTS `binariom`.`estoque` (
  `id` INT(2) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `descricao` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `binariom`.`componente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `binariom`.`componente` ;

CREATE TABLE IF NOT EXISTS `binariom`.`componente` (
  `id` VARCHAR(5) NOT NULL,
  `modelo` VARCHAR(10) NOT NULL,
  `tipo` VARCHAR(30) NOT NULL,
  `marca` VARCHAR(15) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `status` VARCHAR(15) NOT NULL DEFAULT 'DISPONIVEL',
  `id_estoque` INT(2) NOT NULL,
  `equipamento_etiqueta` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_componente_estoque1_idx` (`id_estoque` ASC),
  INDEX `fk_componente_equipamento1_idx` (`equipamento_etiqueta` ASC),
  CONSTRAINT `fk_componente_estoque1`
    FOREIGN KEY (`id_estoque`)
    REFERENCES `binariom`.`estoque` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_componente_equipamento1`
    FOREIGN KEY (`equipamento_etiqueta`)
    REFERENCES `binariom`.`equipamento` (`etiqueta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------

INSERT INTO `cliente` (`matricula`, `nome`, `cpf`, `setor`, `sala`, `telefone`, `senha`, `status`) VALUES
('CL000', 'a', '0', 'A', 0, '0', '0', 'ATIVO'),
('CL111', 'Danilo', '00000000000', 'TI', 1, '00000000000', '123', 'Ativo'),
('CL123', 'GILBERTO SILVA', '100200304', 'A-10', 111, '33912233', 'CL', 'Ativo'),
('CL178', 'ÉRIKA AGUIAR', '100200304', 'A-10', 107, '33895567', 'CL178', 'Ativo'),
('CL456', 'PEDRO HENRIQUE', '1112223334', 'D-20', 245, '73183391', 'CL', 'Ativo'),
('CL987', 'DANILO CAMARGO', '1112223338', 'E-30', 311, '33914557', 'CL', 'Ativo');

-- -----------------------------------------------------

INSERT INTO `estoque` (`id`, `nome`, `descricao`) VALUES
(1, 'Memorias RAM', 'Estoque de Memórias RAM'),
(2, 'HD''s', 'Estoque de HD''s'),
(3, 'Monitores', 'Estoque de Monitores'),
(4, 'Teclado', 'Estoque de Teclados'),
(5, 'Com Defeito', 'Estoque Com Defeito'),
(6, 'Cabos', 'Estoque de Cabos CAT6'),
(7, 'Fonte', 'Estoque de Fontes'),
(8, 'Mouse', 'Estoque de Mouses'),
(9, 'Softwares', 'Estoque de Softwares'),
(10, 'Processadores', 'Estoque de Proecessadores');

-- -----------------------------------------------------

INSERT INTO `equipamento` (`etiqueta`, `tipo`) VALUES
('E000', 'PADRÃO'),
('E190', 'NOTEBOOK'),
('E220', 'DESKTOP');

-- -----------------------------------------------------

INSERT INTO `componente` (`id`, `modelo`, `tipo`, `marca`, `descricao`, `status`, `id_estoque`, `equipamento_etiqueta`) VALUES
('CB001', 'REDE', 'CAT6', 'Mymax', 'Cabo com 305 metros', 'DISPONIVEL', 6, 'E000'),
('CB002', 'REDE', 'CAT6', 'Mymax', 'Cabo com 305 metros', 'DISPONIVEL', 6, 'E190'),
('FT001', 'BLU350ATX', 'BlueCase', 'BlueCase', 'Fonte BlueCase 350W', 'DISPONIVEL', 7, 'E000'),
('FT002', 'BLU350ATX', 'BlueCase', 'BlueCase', 'Fonte BlueCase 350W', 'DISPONIVEL', 7, 'E190'),
('FT003', 'BLU350ATX', 'BlueCase', 'BlueCase', 'Fonte BlueCase 350W', 'DISPONIVEL', 7, 'E220'),
('FT004', 'BLU350ATX', 'BlueCase', 'BlueCase', 'Fonte BlueCase 350W', 'COM DEFEITO', 7, 'E000'),
('FT005', 'BLU350ATX', 'BlueCase', 'BlueCase', 'Fonte BlueCase 350W', 'COM DEFEITO', 7, 'E000'),
('HD001', 'BarraCuda', 'SATA 3,5', 'Seagate', 'HD com 1TB de armazenamento.', 'DISPONIVEL', 2, 'E000'),
('HD002', 'BarraCuda', 'SATA 3,5', 'Seagate', 'HD com 1TB de armazenamento', 'EM USO', 2, 'E220'),
('HD003', 'BarraCuda', 'SATA 3,5', 'Seagate', 'HD com 1TB de armazenamento.', 'EM USO', 2, 'E000'),
('HD004', 'BarraCuda', 'SATA 3,5', 'Seagate', 'HD com 1TB de armazenamento.', 'COM DEFEITO', 2, 'E000'),
('HD005', 'BarraCuda', 'SATA 3,5', 'Seagate', 'HD com 1TB de armazenamento.', 'DISPONIVEL', 2, 'E000'),
('MM001', 'KING-12', 'Memória RAM', 'KINGSTON', 'DDR4, 4GB 2133MHZ', 'COM DEFEITO', 1, 'E000'),
('MN001', '20M37AA-B', 'Monitor', 'LG', 'Monitor LED LG 19 POLEGADAS\r\nWIDESCREEN', 'EM USO', 3, 'E220'),
('MN002', '20M37AA-B', 'Monitor', 'LG', 'Monitor LED LG 19 POLEGADAS', 'COM DEFEITO', 3, 'E000'),
('MN003', '20M37AA-B', 'Monitor', 'LG', 'Monitor LED LG 19 POLEGADAS', 'DISPONIVEL', 3, 'E000'),
('MR001', 'HX318C10F', 'DDR3 SDRAM', 'Kingston', 'HyperX Fury', 'DISPONIVEL', 1, 'E000'),
('MR002', 'HX318C10F', 'DDR3 SDRAM', 'Kingston', 'HyperX Fury', 'DISPONIVEL', 1, 'E000'),
('MR003', 'HX318C10F', 'DDR3 SDRAM', 'Kingston', 'HyperX Fury', 'COM DEFEITO', 1, 'E000'),
('MR004', 'CMU16GX4M2', 'DDR4 DIMM', 'Corsair', 'VENGEANCE LED 16GB', 'EM USO', 1, 'E220'),
('MR005', 'HX421C14FB', 'DDR4', 'Kingston', 'Memória Kingston 4GB', 'DISPONIVEL', 1, 'E000'),
('MR010', 'MR - 224', 'Memoria RAM', 'Kingston', 'Pente 4gb', 'DISPONIVEL', 1, 'E000'),
('MR011', 'MR - 224', 'Memoria RAM', 'Kingston', 'Pente de memÃ³ria 4gb', 'DISPONIVEL', 1, 'E000'),
('MS001', 'Óptico', 'Classic MO179', 'Multilaser', 'Mouse Multilaser', 'DISPONIVEL', 8, 'E000'),
('MS002', 'Óptico', 'Classic MO179', 'Multilaser', 'Mouse Multilaser', 'EM USO', 8, 'E220'),
('MS003', 'Óptico', 'Classic MO179', 'Multilaser', 'Mouse Multilaser', 'COM DEFEITO', 8, 'E000'),
('MS004', 'Óptico', 'Classic MO179', 'Multilaser', 'Mouse Multilaser', 'DISPONIVEL', 8, 'E000'),
('MS005', 'Óptico', 'Classic MO179', 'Multilaser', 'Mouse Multilaser', 'DISPONIVEL', 8, 'E000'),
('SW001', 'Software', 'Windows 7', 'Microsoft', 'Windows 7 Professional', 'DISPONIVEL', 9, 'E190'),
('SW002', 'Software', 'Windows 10', 'Microsoft', 'Windows 10 Home Single Language', 'EM USO', 9, 'E220'),
('TC001', 'K1500', 'TECLADO', 'HP', 'USB 2.0, Branco, PadrÃ£o PT-BR', 'DISPONIVEL', 4, 'E000'),
('TC002', 'TC143', 'TECLADO', 'MULTILASER', 'CONEXAO: USB\r\nCOR: PRETO', 'DISPONIVEL', 4, 'E000');

-- -----------------------------------------------------

INSERT INTO `menu` (`id`, `nome`, `link`) VALUES
(1, 'Inserir Clientes', 'telaAdmin_inserirCliente.jsp'),
(2, 'Lista de Clientes', 'lista_clientes.jsp'),
(3, 'Inserir Usuário', 'telaAdmin_inserirUsuario.jsp'),
(4, 'Lista de Usuários', 'lista_usuarios.jsp'),
(5, 'Inserir Menu', 'telaAdmin_inserirMenu.jsp'),
(6, 'Lista de Menus', 'lista_menus.jsp'),
(7, 'Inserir Perfil', 'telaAdmin_inserirPerfil.jsp'),
(8, 'Lista de Perfis', 'lista_perfis.jsp');

-- -----------------------------------------------------

INSERT INTO `perfil` (`id`, `nome`, `descricao`) VALUES
(1, 'Admin', 'Perfil do Administrador'),
(2, 'Chefe', 'Perfil do Chefe'),
(3, 'Tecnico', 'Perfil dos Tecnicos');

-- -----------------------------------------------------

INSERT INTO `menu_perfil` (`id_menu`, `id_perfil`) VALUES
(1, 1),
(1, 2),
(2, 1),
(2, 2),
(3, 1),
(4, 1),
(5, 1),
(6, 1),
(7, 1),
(8, 1);

-- -----------------------------------------------------

INSERT INTO `usuario` (`matricula`, `nome`, `cpf`, `senha`, `setor`, `telefone`, `status`, `id_perfil`) VALUES
('AD223', 'PEDORO HENRIQUE', '05278640138', 'dark', 'A-10', '33917318', 'Ativo', 1),
('AD459', 'GILBERTO SILVA', '111', '123', 'AD-2', '3391', 'Ativo', 1),
('CH512', 'Pedro Henrique', '05278640138', 'dark', 'A-10', '33917318', 'Ativo', 2),
('TC000', 'AGUARDANDO ATENDIMENTO', '0', '0', 'TI', '0', 'Ativo', 3),
('TC111', 'Gilberto', '000.000.000-00', '123', 'TI-1', '(61)3333-3333', 'Ativo', 3),
('TC324', 'PEDRO HENRIQUE', '05211222133', 'dark', 'TI-1', '33473456', 'Ativo', 3),
('TC387', 'PEDRO HENRIQUE', '011.022.033-04', '123', 'TI-1', '(61)3321-3030', 'Ativo', 3);

-- -----------------------------------------------------

INSERT INTO `chamado` (`bin`, `descricao`, `atendimento`, `status`, `data_abertura`, `data_resolvido`, `usuario_matricula`, `equipamento_etiqueta`, `cliente_matricula`) VALUES
(000001, 'Word apresenta mensagem pedindo para ser ativado', 'Tudo', 'Resolvido', '2017-06-20 18:55:36', '2017-06-28 10:12:51', 'TC324', 'E190', 'CL123'),
(000003, 'Internet oscilando !', 'A internet apresentou oscilação no periodo me que o chamado foi aberto', 'Resolvido', '2017-06-21 22:42:50', '2017-06-28 09:28:25', 'TC324', 'E220', 'CL987'),
(000005, 'Não consigo acessar o YouTube!', '', 'Cancelado', '2017-06-23 22:17:57', '2017-06-28 09:29:16', 'TC324', 'E000', 'CL178'),
(000009, 'teste', '--ATENDIMENTO--', 'Cancelado', '2017-06-28 10:11:38', '2017-06-28 10:12:23', 'TC324', 'E220', 'CL111'),
(000010, 'Meu youtube não abre e eu queria ver o capitulo da novela !', 'Cancelado!', 'Cancelado', '2017-06-28 11:06:11', '2017-06-28 17:52:50', 'TC387', 'E220', 'CL123'),
(000011, 'Meu word estÃ¡ pedindo para ser ativado !', '--ATENDIMENTO--\r\nChave do Word ativado com sucesso !', 'Resolvido', '2017-06-28 11:07:52', '2017-06-28 11:08:46', 'TC387', 'E220', 'CL123'),
(000012, 'Requisito mais teclados para o estoque:\r\n- Multilaser\r\n- USB\r\n', '--ATENDIMENTO--', 'Aprovada', '2017-06-28 21:07:21', '2017-06-28 21:18:37', 'TC324', 'E000', 'CL000');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
